# Generated by Django 5.2.5 on 2025-08-31 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Дата тренировки')),
                ('duration_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('exercise_type', models.CharField(choices=[('rudiments', 'Rudiments'), ('grooves', 'Grooves'), ('fills', 'Fills'), ('songs', 'Songs'), ('freeplay', 'Free Play')], max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Поле для заметок', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
